# Generated by Django 4.2.5 on 2023-09-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='postal_code',
            new_name='postalCode',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='selected_clinic',
            new_name='selectedClinic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
