<script setup>
// Importing necessary utilities from AWS Amplify
import { Amplify } from 'aws-amplify';
// Importing the configuration file generated by AWS Amplify CLI
import config from './amplifyconfiguration.json';
// Configuring Amplify with the imported configuration
Amplify.configure(config);

// Importing the Authenticator component from AWS Amplify UI for Vue
import { Authenticator } from '@aws-amplify/ui-vue';
// Importing the default styles for the Amplify UI components
import '@aws-amplify/ui-vue/styles.css';

// Importing Vue Router utilities for navigation
import { RouterLink, RouterView } from 'vue-router';
// Importing a custom HelloWorld component to be used within the app
import HelloWorld from './components/HelloWorld.vue';

</script>

<template>
  <!-- The Authenticator component wraps around the entire application content,
       making it accessible only to authenticated users -->
  <authenticator>
    <!-- Using a scoped slot to access properties and methods provided by the Authenticator, 
         such as signOut and the current user object -->
    <template v-slot="{ signOut, user }">
      <header>
        <!-- Displaying an application logo -->
        <img alt="Vue logo" class="logo" src="@/assets/logo.svg" width="125" height="125" />

        <div class="wrapper">
          <!-- A custom HelloWorld component with a message prop -->
          <HelloWorld msg="PediaMatch" />

          <!-- Navigation links to different parts of the application -->
          <nav>
            <RouterLink to="/">New Patient Form</RouterLink>
            <RouterLink to="/about">Patient List</RouterLink>
            <!-- Wrap the Sign Out button for consistent navigation styling -->
            <span class="nav-link">
              <button class="sign-out-btn" @click="signOut">Sign Out</button>
            </span>
          </nav>

          <!-- Displaying a greeting message with the username of the authenticated user -->
          <h1>Hello {{ user.signInDetails.loginId }}!</h1>
        </div>
      </header>

      <!-- RouterView renders the component for the matched route -->
      <RouterView />
    </template>
  </authenticator>
</template>

<style scoped>
/* Scoped CSS styles for the App component */
header {
  line-height: 1.5;
  max-height: 100vh;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

/* Styling for the navigation bar */
nav {
  width: 100%;
  font-size: 12px;
  text-align: center;
  margin-top: 2rem;
}

/* Additional styling for active links in the navigation */
nav a.router-link-exact-active {
  color: var(--color-text);
}

nav a.router-link-exact-active:hover {
  background-color: transparent;
}

/* Styling for navigation links and the wrapper around the Sign Out button */
nav a, .nav-link {
  display: inline-block;
  padding: 0 1rem;
  border-right: 1px solid var(--color-border); /* Ensures separation between links and the Sign Out button */
}

/* Removes the right border from the last item in the navigation */
nav .nav-link:last-child {
  border-right: none;
}

/* Hover effect for links and the Sign Out button */
nav a:hover, .sign-out-btn:hover {
  background-color: green; /* Changes background to green on hover for non-selected links/buttons */
}

/* Styling adjustments for the Sign Out button to match link styles */
.sign-out-btn {
  background: none;
  border: none;
  color: inherit;
  font: inherit;
  cursor: pointer;
  text-decoration: none;
  padding: 0; /* Adjust padding if necessary to align with other navigation items */
}


/* Media query for larger screens */
@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }

  nav {
    text-align: left;
    margin-left: -1rem;
    font-size: 1rem;
    padding: 1rem 0;
    margin-top: 1rem;
  }
}
</style>
